require_relative './config/environment'
require 'sinatra/activerecord/rake' # <-- This defines a lot more tasks!

desc "Start our app console"
task :console do
  ActiveRecord::Base.logger = Logger.new(STDOUT)

  binding.pry
end